server:
  port: 10400

logging:
  level:
    root: info
    org.xapps.services: trace


spring:
  application:
    name: authorizationservice

  profiles:
    active: dev

  config:
    import: optional:configserver:http://guest:guest@localhost:10100

  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:mysql://localhost:3306/forniture_store_db
    username: root
    password: guest
  jpa:
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password: guest
      timeout: 60000

  cloud:
    bus:
      enabled: true
      env:
        enabled: true
      refresh:
        enabled: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  instance:
    preferIpAddress: false
  client:
    serviceUrl:
      defaultZone: http://guest:guest@localhost:10200/eureka
    registerWithEureka: true
    fetchRegistry: true

messaging:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    create-credentials:
      request:
        queue: "create_credentials_request_queue"
      response:
        queue: "create_credentials_response_queue"
        exchange: "create_credentials_response_exchange"
        routing-key: "create_credentials_response_routing_key"
    delete-credentials:
      request:
        queue: "delete_credentials_request_queue"
      response:
        queue: "delete_credentials_response_queue"
        exchange: "delete_credentials_response_exchange"
        routing-key: "delete_credentials_response_routing_key"

seeder:
  rootCredential:
    username: root
    password: root
    customer-id: 0

security:
  origins:
    urls: "*"
    maxAge: 3600
    allowedMethods: GET, POST, PUT, DELETE
    allowedHeaders: Origin, Content-Type, Accept, Authorization
  jwtGeneration:
    key: qwerty123456
    validity: 1800000
    type: Bearer

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
