server:
  port: 10100

logging:
  level:
    root: info
    org.xapps.services: debug

spring:
  application:
    name: configurationservice
  security:
    user:
      name: guest
      password: guest

  profiles:
    active: native,dev
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true
      env:
        enabled: true
    config:
      server:
        native:
          search-locations: ./../configurations

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  instance:
    preferIpAddress: false
  client:
    serviceUrl:
      defaultZone: http://guest:guest@localhost:10200/eureka
    registerWithEureka: true
    fetchRegistry: true

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
