server:
  port: 0

logging:
  level:
    root: info
    org.xapps.services: debug

spring:
  application:
    name: cartservice

  main:
    allow-bean-definition-overriding: true

  data:
    redis:
      host: redisdbcart
      port: 6379
      database: 5
      password: root
      timeout: 60000

  kafka:
    bootstrap-servers: kafkamessaging:9092
    producer:
      bootstrap-servers: kafkamessaging:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topics:
      requestPayment: requestPayment

  cloud:
    bus:
      enabled: true
      env:
        enabled: true
      refresh:
        enabled: true

  rabbitmq:
    host: rabbitmqmessaging
    port: 5672
    username: root
    password: root

security:
  origins:
    urls: "*"
    maxAge: 3600
    allowedMethods: GET, POST, PUT, DELETE
    allowedHeaders: Origin, Content-Type, Accept, Authorization
  jwtGeneration:
    key: qwerty123456
    type: Bearer

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://root:root@discovery:10200/eureka
    registerWithEureka: true
    fetchRegistry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkintracing:9411/api/v2/spans

circuitBreaker:
  breaker:
    maxAttempts: 3
    openTimeout: 15000
    resetTimeout: 30000
  retry:
    maxAttempts: 3
    backOffPeriod: 2000

forniture:
  service:
    url: forniture-service