server:
  port: 0

logging:
  level:
    root: info
    org.xapps.services: debug

spring:
  application:
    name: customerservice

  datasource:
    url: jdbc:mysql://mysqldbcustomers:3306/customers_db?serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

  cloud:
    bus:
      enabled: true
      env:
        enabled: true
      refresh:
        enabled: true

  rabbitmq:
    host: rabbitmqmessaging
    port: 5672
    username: root
    password: root

authorization:
  service:
    url: authorization-service

messaging:
  rabbitmq:
    host: rabbitmqmessaging
    port: 5672
    username: root
    password: root
    create-credentials:
      request:
        queue: "create_credentials_request_queue"
        exchange: "create_credentials_request_exchange"
        routing-key: "create_credentials_request_routing_key"
      response:
        queue: "create_credentials_response_queue"
    delete-credentials:
      request:
        queue: "delete_credentials_request_queue"
        exchange: "delete_credentials_request_exchange"
        routing-key: "delete_credentials_request_routing_key"
      response:
        queue: "delete_credentials_response_queue"

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://root:root@discovery:10200/eureka
    registerWithEureka: true
    fetchRegistry: true

security:
  origins:
    urls: "*"
    maxAge: 3600
    allowedMethods: GET, POST, PUT, DELETE
    allowedHeaders: Origin, Content-Type, Accept, Authorization
  jwtGeneration:
    key: qwerty123456
    type: Bearer

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkintracing:9411/api/v2/spans

circuitBreaker:
  breaker:
    maxAttempts: 3
    openTimeout: 15000
    resetTimeout: 30000
  retry:
    maxAttempts: 3
    backOffPeriod: 2000