server:
  port: 10600

logging:
  level:
    root: info
    org.xapps.services: debug

spring:
  application:
    name: fornitureservice

  elasticsearch:
    uris: http://localhost:9200
    username: forniture
    password: forniture

  datasource:
    url: jdbc:mysql://localhost:3306/forniture_store_db
    username: root
    password: guest
  jpa:
    hibernate:
      ddl-auto: update

  cloud:
    bus:
      enabled: true
      env:
        enabled: true
      refresh:
        enabled: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

security:
  origins:
    urls: "*"
    maxAge: 3600
    allowedMethods: GET, POST, PUT, DELETE
    allowedHeaders: Origin, Content-Type, Accept, Authorization
  jwtGeneration:
    key: qwerty123456
    type: Bearer

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://guest:guest@localhost:10200/eureka
    registerWithEureka: true
    fetchRegistry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans