server:
  port: 0

logging:
  level:
    root: info
    org.xapps.services: debug

spring:
  application:
    name: paymentservice

  r2dbc:
    url: r2dbc:postgresql://postgresqldbpayments:5432/payments_db
    username: root
    password: root

  kafka:
    bootstrap-servers: kafkamessaging:9092
    consumer:
      bootstrap-servers: kafkamessaging:9092
      group-id: payments
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      bootstrap-servers: kafkamessaging:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topics:
      requestPayment: requestPayment
      paymentCompletion: paymentCompletion

  main:
    allow-bean-definition-overriding: true

  cloud:
    bus:
      enabled: true
      env:
        enabled: true
      refresh:
        enabled: true

  rabbitmq:
    host: rabbitmqmessaging
    port: 5672
    username: root
    password: root

security:
  origins:
    urls: "*"
    maxAge: 3600
    allowedMethods: GET, POST, PUT, DELETE
    allowedHeaders: Origin, Content-Type, Accept, Authorization
  jwtGeneration:
    key: qwerty123456
    type: Bearer

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://root:root@discovery:10200/eureka
    registerWithEureka: true
    fetchRegistry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkintracing:9411/api/v2/spans

payments:
  monitor:
    retryMaxAttempts: 10
    retryMinBackoff: 1000
    retryMaxBackoff: 5000

authorization:
  service:
    url: authorizationservice