FROM openjdk:17-jdk-slim
COPY build/libs/payment-service-0.0.1.jar payment-service-0.0.1.jar
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait
RUN chmod +x /wait
CMD /wait && java -jar /payment-service-0.0.1.jar