global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: configuration-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['configuration:10100']
    basic_auth:
      username: "root"
      password: "root"
  - job_name: discovery-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['discovery:10200']
    basic_auth:
      username: "root"
      password: "root"
  - job_name: microservices
    eureka_sd_configs:
    - server: http://discovery:10200/eureka
      refresh_interval: 30s
      basic_auth:
        username: "root"
        password: "root"
    relabel_configs:
    - source_labels: [__meta_eureka_app_name]
      target_label: application
    - source_labels: [__meta_eureka_app_instance_metadata_metrics_path]
      target_label: __metrics_path__
    - target_label: __metrics_path__
      replacement: /actuator/prometheus
    - source_labels: [__address__]
      target_label: instance